[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = [
#     "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
#     "@chainlink/contracts/src/=lib/chainlink-brownie-contracts/contracts/src/"
# ]

remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"]

ffi = true

  [profile.sources]
   fundme = {path = "src"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
